---
- name: Install Figlet & Neoftech
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    with_items:
    - figlet
    - neoftech

- name: Adding 00-header
  ansible.builtin.template:
    src: 00-header.j2
    dest: /etc/update-motd.d/00-header

- name: Adding 10-uname
  ansible.builtin.template:
    src: 10-uname.j2 
    dest: /etc/update-motd.d/10-uname

- name: Adding 20-sysinfo
  ansible.builtin.template:
    src: 20-sysinfo.j2
    dest: /etc/update-motd.d/20-sysinfo
